---
- hosts: docker_hosts

  vars:
    test_image: arm32v7/hello-world

  tasks:

    - name: "Install prerequisite packages"
      become: yes
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - python
        - python-setuptools
        - python3
        - python3-setuptools
        - software-properties-common

    - name: "Install pip"
      become: yes
      easy_install:
        executable: "{{ item }}"
        name: pip
        state: latest
      with_items:
        - easy_install-2.7
        - easy_install-3.4

    - name: "Install docker-py"
      become: yes
      pip:
        executable: "{{ item }}"
        name:
          - docker-py
          - pip
        state: latest
      with_items:
        - pip2
        - pip3

    - name: "Install Docker"
      become: yes
      shell: curl -sSL https://get.docker.com/ | sh

    - name: "Add docker group"
      become: yes
      group:
        name: docker
        state: present

    - name: "Add pi user to docker group"
      become: yes
      user:
        name: pi
        groups:
          - docker
        append: yes
        state: present

    - name: "Ensure that the Docker installation works"
      become: yes
      docker_container:
        image: "{{ test_image }}"
        name: hello
        cleanup: yes
        state: started

    - name: "Remove hello_world image"
      become: yes
      docker_image:
        name: "{{ test_image }}"
        state: absent
        force: yes
