---
- hosts: docker_hosts
  become: yes

  vars:
    test_image: arm32v7/hello-world

  tasks:

    - name: "Install prerequisite packages"
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - python
        - python-setuptools
        - python3
        - python3-setuptools
        - software-properties-common

    - name: "Install pip"
      easy_install:
        executable: "{{ item }}"
        name: pip
        state: latest
      with_items:
        - easy_install-2.7
        - easy_install-3.4

    - name: "Install docker-py"
      pip:
        executable: "{{ item }}"
        name:
          - docker-py
          - pip
        state: latest
      with_items:
        - pip2
        - pip3

    - name: "Install Docker"
      shell: curl -sSL https://get.docker.com/ | sh

    - name: "Ensure systemd drop-in directory exist"
      file:
        state: directory
        path: /etc/systemd/system/docker.service.d

    - name: "Create systemd override for Docker"
      template:
        src: override.conf.j2
        dest: /etc/systemd/system/docker.service.d/override.conf
      register: systemd

    - name: "Configure Docker daemon"
      tags: test
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
      register: daemon_config

    - name: "Restart Docker daemon"
      systemd:
        name: docker
        daemon_reload: yes
        state: restarted
      when: daemon_config.changed or systemd.changed

    - name: "Ensure that the Docker installation works"
      docker_container:
        image: "{{ test_image }}"
        name: hello
        cleanup: yes
        state: started

    - name: "Remove hello_world image"
      docker_image:
        name: "{{ test_image }}"
        state: absent
        force: yes
